### ISSUE TITLE
Active smb shares don't working

### ISSUE THREAD

**Issue by yanalp73** [jmichault/motioneye.eo#23]
hello (my english is not very good)
i use MotionEye [22.4.1](url)
i want to ativate smb shares in motioneye
1)i active the smb_shares in motioeye.conf
2)i reboot the machine
3)i open webpage ip:8765
4) i'm login
5) then then application apen a black windows only with logo motionEye
6) and not working

In motonEye status, i have error:
-motioneye.service: Main process exited, code=exited, status=255/EXCEPTION
-motioneye.service : Failed with result 'exit-code'

How can i resolve problem, please
Thanks a lot

**Comment by jmichault** [comment]
Hello,
I have tested smb shares, and it works on my PC.
Prerequisites are :
* cifs-utils installed. If not, on debian or ubuntu, do :
 ` sudo apt install cifs-utils`
* /media directory must exists
* motioneye must be run as root : 
```
sudo systemctl stop motioneye 
sudo sed -i 's/User=motion/User=root/' /etc/systemd/system/motioneye.service 
sudo systemctl daemon-reload
sudo systemctl start motioneye
```

**Comment by yanalp73** [comment]
Hello,
It's all good
thanks !
